### ISSUE TITLE
Is it for beginners?

### ISSUE THREAD

**Issue by MrMuMu** [nxrighthere/UnrealCLR#10]
Hello,

First of all your project made me very excited, thank you for your hard work.

I have joined to the gaming club recently with Unity because I know c#. How easy it is for a newbie to start learning Unreal with UnrealCLR who is experienced in C#?

Also how complete are the api and docs?

**Comment by nxrighthere** [comment]
Assuming that we are comparing it with Unity, the learning curve is about the same, but you have more freedom here in terms of toolset and tight connection with the .NET ecosystem. What is not very intuitive is how to structure your code and execution pipeline through blueprints since there's no interlayer between your code and the runtime rather than assemblies loading with the framework.

Same as with a regular .NET application where you have the `Main()` method, which is the entry point of the program, you have to instruct the runtime from where to kick-start the logic of your game/application. If you want, you can also implement an intermediate scripts manager or any other similar system at your choice, the plugin was created with flexibility in mind.

In terms of API completeness, please, see the [roadmap](https://github.com/users/nxrighthere/projects/5?fullscreen=true) and [API reference](https://github.com/nxrighthere/UnrealCLR/blob/master/API/UnrealEngine-Framework.md). Generally speaking, the framework can be used for making games in the current state, but since the plugin is in the preview stage, things might change significantly.

**Comment by nxrighthere** [comment]
To get an idea of how to start working with the plugin, follow the installation instruction and run [test scripts](https://github.com/nxrighthere/UnrealCLR/tree/master/Source/Managed/Tests).

A guide on how to structure the execution pipeline in an optimal way will be provided later. If you are familiar with blueprints, you will figure this out pretty quickly through the extraction of data from blueprint classes and making macros.

**Comment by MrMuMu** [comment]
Thank you for the detailed answer. I will stop by with .NET 5.
